version: "3"

services:

  scylla-node1:
    container_name: scylla-node1
    image: scylladb/scylla:4.5.0
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    volumes:
      - "${PWD}/scylla_configs/scylla.yaml:/etc/scylla/scylla.yaml"
      - "${PWD}/scylla_configs/cassandra-rackdc.properties.rk1:/etc/scylla/cassandra-rackdc.properties"
      - "${PWD}/scylla_configs/mutant-data.txt:/mutant-data.txt"
    networks:
      web:

  scylla-node2:
    container_name: scylla-node2
    image: scylladb/scylla:4.5.0
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    volumes:
      - "${PWD}/scylla_configs/scylla.yaml:/etc/scylla/scylla.yaml"
      - "${PWD}/scylla_configs/cassandra-rackdc.properties.rk2:/etc/scylla/cassandra-rackdc.properties"
      - "${PWD}/scylla_configs/mutant-data.txt:/mutant-data.txt"
    networks:
      web:

  scylla-node3:
    container_name: scylla-node3
    image: scylladb/scylla:4.5.0
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    volumes:
      - "${PWD}/scylla_configs/scylla.yaml:/etc/scylla/scylla.yaml"
      - "${PWD}/scylla_configs/cassandra-rackdc.properties.rk3:/etc/scylla/cassandra-rackdc.properties"
      - "${PWD}/scylla_configs/mutant-data.txt:/mutant-data.txt"
    networks:
      web:

networks:
  web:
    driver: bridge