version: "3"

services:
  client:
    container_name: "robo-client"
    image: "teleporttacos/client:v1"
    depends_on:
      - server
    environment:
      API_SERVER_URL: "server"
      GRPC_SERVER_LISTEN_PORT: "9999"
    networks:
      demo:
        aliases: 
          - "robo-client"
 # controller container holds ansible
  controller:
    # the command to run when the container is executed
    command: ["/usr/bin/sleep", "100000000"]
    # name the container for service discovery as well
    # as this will be the name output from `docker compose ps`
    container_name: "controller"
    # name the image created from the build step above
    # image: "ansible-demo"
    image: scylla-node:v1
    # attach the running container to the below network(s)
    networks:
      # put the container in the network named "demo"
      # this network is defined below
      demo:
        # set up service discovery in the network to reference
        # this container by the name "controller"
        aliases:
          - "controller"
    # attach any volumes inside of the container. This is
    # done so that ansible files on the host system
    # can be accessed from within the controller container
    # since ansible will be ran from here becuase it
    # will be on the same docker network as the other 
    # containers being orchestrated and demonstrated.
    volumes:
        - "./:/root/ansible"

  scylla-node1:
    container_name: scylla-node1
    image: scylla-node:v1
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    deploy:
      resources:
        reservations:
          cpus: "2"
          memory: "1G"
    networks:
      demo:

  scylla-node2:
    container_name: scylla-node2
    image: scylla-node:v1
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    deploy:
      resources:
        reservations:
          cpus: "2"
          memory: "1G"
    networks:
      demo:

  scylla-node3:
    container_name: scylla-node3
    image: scylla-node:v1
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    deploy:
      resources:
        reservations:
          cpus: "2"
          memory: "1G"
    networks:
      demo:

  server:
    container_name: "server"
    image: "teleporttacos/server:v1"
    depends_on:
      - scylla-node1
      - scylla-node2
      - scylla-node3
    environment:
      GRPC_SERVER_LISTEN_PORT: "9999"
      HTTP_SERVER_LISTEN_PORT: "9080"
      # SCYLLA_SERVERS: '"scylla-node1", "scylla-node2, "scylla-node3"'
    networks:
      demo:
        aliases: 
          - "server"
    ports:
      - 9080:9080

networks:
  demo:
    driver: bridge