

- name: "introduction to ansible"
  hosts: "all"

  tasks:

    - name: "copy config file"
      ansible.builtin.copy:
        src: "foo.conf"
        dest: "/etc/foo.conf"
        group: "root"
        mode: 0644
        owner: "root"