

- name: "introduction to ansible"
  hosts: "all"
  gather_facts: true

  vars: 
    message: "Hello Scylla Summit!"

  tasks:

    - name: "copy file"
      ansible.builtin.copy:
        content: "{{ message }}"
        dest: "/tmp/message.txt"
        group: "root"
        mode: 0600
        owner: "root"