version: '3'

tasks:

  # build the custom Docker images needed for the demo
  build:
    cmds:
      - docker build -f ./dockerfile -t scylla-node:v1 .

  # shorten the commands to run ansible inside of docker
  demo:
    cmds:
      - docker compose exec controller /bin/bash

  # shorten the command to show server logs
  logs:
    cmds:
      - docker compose logs -f server

  # shorten and filter the docker compose command to show running containers
  ps:
    cmds: 
      - docker compose ps | awk '{ print $1 }'

  # shorten the command to run nodetool status inside of a scylla node
  status:
    cmds:
      - docker compose exec scylla-node1 nodetool status

  # shorten the commands to stand up the demo
  up:
    cmds:
      - docker compose up -d